services:
  client_service:
    image: react-app-npm
    build: ./client_service
    container_name: client_service_tomford
    ports:
      - "3000:3000"
    volumes:
      - "./client_service:/app/client_service:delegated"
      - /app/client_service/node_modules/
    stdin_open: true
    networks:
      - tomford-network
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - tomford-network
    depends_on:
      - client_service

networks:
  tomford-network:
    driver: bridge