spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tom_ford
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-wait: 10000
      max-active: 10
      initial-size: 5
      min-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect